
#
# This LookML file was generated by AtScale on 2022-11-21T13:19:23.894603Z
#
# AtScale engine version: 2022.2.0.11610
# AtScale DesignCenter version: 2022.2.0.19507
# AtScale version: 2022.2.0.4819
# Organization: default
# Project: WS2

connection: "connected_feature_analytics"
label: "WS2"


include: "/views/WS2/WS2.view.lkml"


explore: WS2 {
  label: "WS2"
}

